#!/usr/bin/env python

import sys
import os
import shutil

sys.path.append(".")
from config import *

v = vars()

try:
    os.mkdir("_releases")
except OSError:
    pass

shutil.copy("_build/%(app)s.xpi" % v, "_releases/%(updateFile)s" % v)
print "_releases/%(updateFile)s" % v
