#!/bin/bash

export APP=updatescan

# First do a release build and package it up
./install.rdf.build
./chrome.manifest.build
rm -f $APP.xpi
./xpi.build

# Now do a dev build and leave unpackaged
./install.rdf.build dev
./chrome.manifest.build dev
