#!/usr/bin/env python

from config import *
from os import system, remove, listdir
from shutil import copy

v = vars()

system("./www/update.rdf.build")

copy("%(app)s.xpi" % v, "www/%(app)s.xpi" % v)
copy("%(app)s.xpi" % v, "www/%(updateFile)s" % v)

comment = "Published "+app+" "+version+" build"

system("svn add www/%(updateFile)s" % v)
system("svn ci -m '"+comment+"' " +
    "www/%(app)s.xpi www/%(updateFile)s www/update.rdf" % v)
