#!/usr/bin/env python

from config import *
from os import system, remove, listdir
from shutil import copy

v = vars()

#system("./releases/update.rdf.build")

copy("%(app)s.xpi" % v, "releases/%(app)s.xpi" % v)
copy("%(app)s.xpi" % v, "releases/%(updateFile)s" % v)
print "releases/%(updateFile)s" % v

#comment = "Published "+app+" "+version+" build"
#system("svn add releases/%(updateFile)s" % v)
#system("svn ci -m '"+comment+"' " +
#    "releases/%(app)s.xpi releases/%(updateFile)s releases/update.rdf" % v)
